# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
    - git fetch --unshallow || true
    # Cancel building pull requests when there aren't changed in the docs directory.
    # If there are no changes (git diff exits with 0) we force the command to return with 183.
    # This is a special exit code on Read the Docs that will cancel the build immediately.
    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' '.readthedocs.yaml';
      then
        exit 183;
      fi
    pre_build:
      # 1. Download gh CLI
      - wget https://github.com/cli/cli/releases/download/v2.40.0/gh_2.40.0_linux_amd64.tar.gz
      # 2. Extract it
      - tar -xf gh_2.40.0_linux_amd64.tar.gz
      # 3. Move binary to a local bin folder
      - mkdir -p $HOME/bin
      - cp gh_2.40.0_linux_amd64/bin/gh $HOME/bin/gh
      # 4. Verify it works
      - $HOME/bin/gh --version
      # 5. Run the script with the PATH and TOKEN set specifically for this command
      #    We add $HOME/bin to PATH so the script can just say 'gh' instead of full path
      #    We map RTD_TOKEN to GITHUB_TOKEN so gh finds it automatically
      - PATH=$HOME/bin:$PATH GITHUB_TOKEN=$RTD_TOKEN SOURCEDIR=. BUILDDIR=$READTHEDOCS_OUTPUT bash docs/jobs/pre-build-job.sh

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
- pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
